### ISSUE TITLE
actualize_script.php - Cannot pass parameter 2 by reference

### ISSUE THREAD

**Issue by fpeterschmitt** [FreshRSS/FreshRSS#1349]
Hi,

I run FreshRSS `1.6.0`.

I don't know if it's specific to PHP7, but i caught this error:

```
$ php /srv/freshrss/FreshRSS/app/actualize_script.php 
Starting feed actualization at 2016-11-02T13:56:35+01:00
Actualize florent...
PHP Fatal error:  Uncaught Error: Cannot pass parameter 2 by reference in /srv/freshrss/FreshRSS/app/Models/EntryDAO.php:201
Stack trace:
#0 /srv/freshrss/FreshRSS/app/Controllers/feedController.php(339): FreshRSS_EntryDAO->updateEntry(Array)
#1 /srv/freshrss/FreshRSS/app/Controllers/feedController.php(455): FreshRSS_feed_Controller::actualizeFeed(false, false, '1')
#2 /srv/freshrss/FreshRSS/lib/Minz/Dispatcher.php(119): FreshRSS_feed_Controller->actualizeAction()
#3 /srv/freshrss/FreshRSS/lib/Minz/Dispatcher.php(48): Minz_Dispatcher->launchAction('actualizeAction')
#4 /srv/freshrss/FreshRSS/lib/Minz/FrontController.php(84): Minz_Dispatcher->run()
#5 /srv/freshrss/FreshRSS/app/actualize_script.php(65): Minz_FrontController->run()
#6 {main}
  thrown in /srv/freshrss/FreshRSS/app/Models/EntryDAO.php on line 201
```

I modified `EntryDAO.php` line 201 so it works now:

```
$__patch_valuesTmp_isread = $valuesTmp['is_read'] ? 1 : 0;
$this->updateEntryPrepared->bindParam(':is_read', $__patch_valuesTmp_isread, PDO::PARAM_INT);
```

**Comment by Alkarex** [comment]
Thanks for the bug report. Indeed, that looks like an error on our side. Could you please try with

``` php
        if ($valuesTmp['is_read'] !== null) {
            $this->updateEntryPrepared->bindValue(':is_read', $valuesTmp['is_read'] ? 1 : 0, PDO::PARAM_INT);
        }
```

**Comment by fpeterschmitt** [comment]
Yes sir! It works, i got my feeds updated :)

**Comment by Alkarex** [comment]
Fixed in https://github.com/FreshRSS/FreshRSS/pull/1350
I will release a version 1.6.1 to address this regression.
