### ISSUE TITLE
Postgres SSL connection string

### ISSUE THREAD

**Issue by xoxys** [FreshRSS/FreshRSS#2549]
I've tried to set up FreshRSS with Postgres SSL connection. Therefore, I have added following to the config file:
```
'host': postgres.example.com;port=5432;sslmode=verify-full;sslrootcert=/etc/ssl/certs/ca-certificates.crt
```

but this does not work, because the complete path is removed by some filter functions. Running e.g. `/usr/bin/php -f /var/www/app/app/actualize_script.php` results in:
```
PHP Fatal error:  Uncaught Minz_PDOConnectionException: Access to database is denied for `pgfreshrss` (`pgsql:host=postgres.example.com;port=5432;sslrootcert=;sslmode=verify-full;dbname=freshrss`) in /var/www/app/lib/Minz/ModelPdo.php:95
```

As you can see, the path to the root ca was completely dropped (for whatever reason). As a workaround I created a symlink of /etc/ssl/certs/ca-certificates.crt into FreshRSS root dir and simply pass `sslrootcert=ca-certificates.crt` to the connection string. 

While this workaround works as expected, it would be cool to get a better Postgres ssl support.

**Comment by Alkarex** [comment]
For reference: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS
I think we should expose a new parameter (not `host`) to add additional connection parameters, both in the Web install and CLI install.

**Comment by xoxys** [comment]
Cool! Thanks for your fast response 🙂

**Comment by Alkarex** [comment]
@xoxys Could you please test this fix? https://github.com/FreshRSS/FreshRSS/pull/2552
It should allow you to add in your `data/config.php` something like:

```php
...
db => [
...
'connection_uri_params': 'sslmode=verify-full;sslrootcert=/etc/ssl/certs/ca-certificates.crt',
...
],
...
```

**Comment by Alkarex** [comment]
P.S.: I can merge in our /dev branch if it makes it easier to test for you

**Comment by xoxys** [comment]
@Alkarex cool. No thats fine, no merge needed. I have to rebuild my own docker container and will patch the file manually. Thanks for your work!

**Comment by xoxys** [comment]
@Alkarex ok, so I've added the appropriate changes. If I don't specify the path to the root ca I can see the expected SSL error in the log on my database server. After I added the full configuration string `'connection_uri_params' => 'sslmode=verify-full;sslrootcert=/etc/ssl/certs/ca-certificates.crt'` I can't login anymore to FreshRSS (nothing in Postgres log) and got following Exception:

```
[05-Oct-2019 12:50:59] WARNING: [pool www] child 34 said into stderr: "[05-Oct-2019 14:50:59 Europe/Berlin] PHP Notice:  Undefined property: FreshRSS_CategoryDAO::$prefix in /var/www/app/app/Models/CategoryDAO.php on line 117"
[05-Oct-2019 12:50:59] WARNING: [pool www] child 34 said into stderr: "[05-Oct-2019 14:50:59 Europe/Berlin] PHP Notice:  Undefined property: FreshRSS_CategoryDAO::$prefix in /var/www/app/app/Models/CategoryDAO.php on line 118"
[05-Oct-2019 12:50:59] WARNING: [pool www] child 34 said into stderr: "[05-Oct-2019 14:50:59 Europe/Berlin] PHP Notice:  Undefined property: FreshRSS_CategoryDAO::$bd in /var/www/app/app/Models/CategoryDAO.php on line 122"
[05-Oct-2019 12:50:59] WARNING: [pool www] child 34 said into stderr: "[05-Oct-2019 14:50:59 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in /var/www/app/app/Models/CategoryDAO.php:122"
[05-Oct-2019 12:50:59] WARNING: [pool www] child 34 said into stderr: "Stack trace:"
[05-Oct-2019 12:50:59] WARNING: [pool www] child 34 said into stderr: "#0 /var/www/app/app/Controllers/indexController.php(176): FreshRSS_CategoryDAO->listCategories()"
[05-Oct-2019 12:50:59] WARNING: [pool www] child 34 said into stderr: "#1 /var/www/app/app/Controllers/indexController.php(30): FreshRSS_index_Controller->updateContext()"
[05-Oct-2019 12:50:59] WARNING: [pool www] child 34 said into stderr: "#2 /var/www/app/lib/Minz/Dispatcher.php(118): FreshRSS_index_Controller->normalAction()"
[05-Oct-2019 12:50:59] WARNING: [pool www] child 34 said into stderr: "#3 /var/www/app/lib/Minz/Dispatcher.php(47): Minz_Dispatcher->launchAction('normalAction')"
[05-Oct-2019 12:50:59] WARNING: [pool www] child 34 said into stderr: "#4 /var/www/app/lib/Minz/FrontController.php(84): Minz_Dispatcher->run()"
[05-Oct-2019 12:50:59] WARNING: [pool www] child 34 said into stderr: "#5 /var/www/app/p/i/index.php(48): Minz_FrontController->run()"
[05-Oct-2019 12:50:59] WARNING: [pool www] child 34 said into stderr: "#6 {main}"
[05-Oct-2019 12:50:59] WARNING: [pool www] child 34 said into stderr: "  thrown in /var/www/app/app/Models/CategoryDAO.php on line 122"
```

Maybe I did something wrong?

**Comment by Alkarex** [comment]
@xoxys The patch is for the /dev branch. It would not work on the /master branch

**Comment by Alkarex** [comment]
@xoxys I have merged the patch in the /dev branch, so you can just directly test https://github.com/FreshRSS/FreshRSS/tree/dev

**Comment by xoxys** [comment]
Ok got it. Works for me now. One small hint. Maybe you should add `$dsnParams` also to the `Minz_PDOConnectionException` blog for debugging purpose.

https://github.com/Alkarex/FreshRSS/blob/f1173f96c44e776a44f927933db4e4eb46776bd6/lib/Minz/ModelPdo.php#L91-L93

**Comment by Alkarex** [comment]
@xoxys Good idea. Would you mind making a pull request?

```php
			throw new Minz_PDOConnectionException(
				$dsn . $dsnParams,
				$db['user'], Minz_Exception::ERROR
			);
```

**Comment by xoxys** [comment]
@Alkarex yeah I'll prepare one

**Comment by xoxys** [comment]
@Alkarex Sorry for the wrong PR...

**Comment by Alkarex** [comment]
@xoxys No worries, thanks, and please add a line for you in https://github.com/FreshRSS/FreshRSS/blob/dev/CREDITS.md
