### ISSUE TITLE
cli failing with Current user must not be empty

### ISSUE THREAD

**Issue by X-dark** [FreshRSS/FreshRSS#2644]
Hi,
I am having some difficulties to use the cli with 1.15.1.

Commands involving specific user return errors similar to 
```
PHP Fatal error:  Uncaught Minz_PDOConnectionException: Access to database is denied for `` (`Current user must not be empty!`) in /usr/share/webapps/freshrss/lib/Minz/ModelPdo.php:32
```

For the user-info cli, this fix is enough:
```patch
--- cli/user-info.php.orig      2019-11-08 12:46:30.386059564 +0100
+++ cli/user-info.php   2019-11-08 12:36:37.834287942 +0100
@@ -43,7 +43,7 @@
 foreach ($users as $username) {
        $username = cliInitUser($username);
 
-       $catDAO = FreshRSS_Factory::createCategoryDao();
+       $catDAO = FreshRSS_Factory::createCategoryDao($username);
        $feedDAO = FreshRSS_Factory::createFeedDao($username);
        $entryDAO = FreshRSS_Factory::createEntryDao($username);
        $tagDAO = FreshRSS_Factory::createTagDao($username);
```

But for export-sqlite-for-user it seems less obvious. Here the full error in this case:
```
FreshRSS exporting database to SQLite for user “girardc”…
PHP Fatal error:  Uncaught Minz_PDOConnectionException: Access to database is denied for `` (`Current user must not be empty!`) in /usr/share/webapps/freshrss/lib/Minz/ModelPdo.php:32
Stack trace:
#0 /usr/share/webapps/freshrss/app/Models/Factory.php(6): Minz_ModelPdo->__construct(false)
#1 /usr/share/webapps/freshrss/app/Models/DatabaseDAO.php(201): FreshRSS_Factory::createUserDao()
#2 /usr/share/webapps/freshrss/cli/export-sqlite-for-user.php(26): FreshRSS_DatabaseDAO->dbCopy('/tmp/freshrss-g...', 1)
#3 {main}
  thrown in /usr/share/webapps/freshrss/lib/Minz/ModelPdo.php on line 32
```

Is this related to a specific config error on my part or a recent change to Models classes that break behavior?

**Comment by X-dark** [comment]
Found the culprit (cf my comment on #2635 )

**Comment by Alkarex** [comment]
@X-dark Could you please try this candidate fix? https://github.com/FreshRSS/FreshRSS/pull/2646
