### ISSUE TITLE
Uncaught TypeError: ceil(): Argument #1 ($num) must be of type int|float, string given

### ISSUE THREAD

**Issue by hrehfeld** [FreshRSS/FreshRSS#3401]
I'm on 1.17.1-dev, docker: 

```
freshrss       | FreshRSS[164]: SimplePie GET http://podcast.hr2.de/derTag/podcast.xml
freshrss       | PHP Fatal error:  Uncaught TypeError: ceil(): Argument #1 ($num) must be of type int|float, string given in /var/www/FreshRSS/lib/SimplePie/SimplePie/Item.php:2871
freshrss       | Stack trace:
freshrss       | #0 /var/www/FreshRSS/lib/SimplePie/SimplePie/Item.php(2871): ceil()
freshrss       | #1 /var/www/FreshRSS/lib/SimplePie/SimplePie/Item.php(1062): SimplePie_Item->get_enclosures()
freshrss       | #2 /var/www/FreshRSS/lib/SimplePie/SimplePie/Item.php(937): SimplePie_Item->get_enclosure()
freshrss       | #3 /var/www/FreshRSS/app/Models/Feed.php(371): SimplePie_Item->get_permalink()
freshrss       | #4 /var/www/FreshRSS/app/Controllers/feedController.php(354): FreshRSS_Feed->loadEntries()
freshrss       | #5 /var/www/FreshRSS/app/Controllers/feedController.php(548): FreshRSS_feed_Controller::actualizeFeed()
freshrss       | #6 /var/www/FreshRSS/lib/Minz/Dispatcher.php(119): FreshRSS_feed_Controller->actualizeAction()
freshrss       | #7 /var/www/FreshRSS/lib/Minz/Dispatcher.php(47): Minz_Dispatcher->launchAction()
freshrss       | #8 /var/www/FreshRSS/lib/Minz/FrontController.php(81): Minz_Dispatcher->run()
freshrss       | #9 /var/www/FreshRSS/app/actualize_script.php(75): Minz_FrontController->run()
freshrss       | #10 {main}
freshrss       |   thrown in /var/www/FreshRSS/lib/SimplePie/SimplePie/Item.php on line 2871
```

**Comment by Alkarex** [comment]
Hello,
Which more precise tag are you using: `freshrss/freshrss:latest` ?

**Comment by Alkarex** [comment]
This feed uses an empty length, which crashes with PHP 8+

```xml
<enclosure url="https://mp3podcasthr-a.akamaihd.net:443/mp3/podcast/derTag/derTag_20210129_87093232.mp3" length="" type="audio/mpeg"/>
```

Fix coming

**Comment by Alkarex** [comment]
Fix ready https://github.com/FreshRSS/FreshRSS/pull/3404

**Comment by hrehfeld** [comment]
Seems to be fixed after updating! :+1:
