### ISSUE TITLE
[BUG] Unable to Import

### ISSUE THREAD

**Issue by bl-ey** [FreshRSS/FreshRSS#4590]
Probably more user error than bug - hoping someone can see something I don't.

**Describe the bug**
Unable to import through multiple routes.

**To Reproduce**

**Web Attempt:**
1. Navigate to `/p/i/?c=importExport`
2. Select Import
3. Select `.xml` from local
Result:
Blank page - 500 internal error in console -
```
HTTP/1.0 500 Internal Server Error
Date: Wed, 07 Sep 2022 21:14:34 GMT
Server: Apache/2.4.54 (Debian)
Cache-Control: private, must-revalidate, max-age=0
Last-Modified: Wed, 07 Sep 2022 21:14:34 GMT
Etag: "12277580bb0ee25974e8b6b70ed2c384"
Content-Length: 0
Connection: close
Content-Type: text/html; charset=UTF-8 
```
Request Body:
```
<opml version="2.0">
	<body>
		<outline text="Subscriptions" title="Subscriptions">
			<outline xmlUrl='<RSSBRIDGEURL>' />
<outline xmlUrl='<RSSBRIDGEURL>' />
<outline xmlUrl='<RSSBRIDGEURL>' />
<outline xmlUrl='<RSSBRIDGEURL>' />
		</outline>
	</body>
</opml>
```

**CLI Attempt:**
1. Navigate to `/usr/share/FreshRSS/cli
2. Run `./cli/import-for-user.php --user username --filename /path/to/file.ext`
Result:
```
FreshRSS failed requirements:
• data
• cache
• users
• favicons
```

Logs:
`/var/log/error.default.log`
```
[Wed Sep 07 22:14:34.827678 2022] [php7:warn] [pid 1514974] [client <networkdeviceip>] PHP Warning:  libopml_parse_string(): Node no longer exists in /usr/share/FreshRSS/lib/lib_opml.php on line 194
[Wed Sep 07 22:14:34.830214 2022] [php7:notice] [pid 1514974] [client <networkdeviceip>] PHP Notice:  Undefined index: text in /usr/share/FreshRSS/app/Services/ImportService.php on line 138   
[Wed Sep 07 22:14:34.830907 2022] [php7:error] [pid 1514974] [client <networkdeviceip>] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to FreshRSS_Feed::_name() must be of the type string, null given, called in /usr/share/FreshRSS/app/Services/ImportService.php on line 153 and defined in /usr/share/FreshRSS/app/Models/Feed.php:283\nStack trace:\n#0 /usr/share/FreshRSS/app/Services/ImportService.php(153): FreshRSS_Feed->_name()\n#1 /usr/share/FreshRSS/app/Services/ImportService.php(91): FreshRSS_Import_Service->addFeedOpml()\n#2 /usr/share/FreshRSS/app/Services/ImportService.php(279): FreshRSS_Import_Service->addOpmlElements()\n#3 /usr/share/FreshRSS/app/Services/ImportService.php(106): FreshRSS_Import_Service->addCategoryOpml()\n#4 /usr/share/FreshRSS/app/Services/ImportService.php(56): FreshRSS_Import_Service->addOpmlElements()\n#5 /usr/share/FreshRSS/app/Controllers/importExportController.php(102): FreshRSS_Import_Service->importOpml()\n#6 /usr/share/FreshRSS/app/Controllers/importExportController.php(173): FreshRSS_importExport_Controller->importFile()\n#7 /usr/share/FreshRSS/lib/Minz/Dispatcher.php(119): Fres in /usr/share/FreshRSS/app/Models/Feed.php on line 283
```
`/var/log/access.default.log`
```
<localhost>:<customport> <networkdeviceip> - - [07/Sep/2022:22:11:02 +0100] "POST /p/i/?c=importExport&a=import HTTP/1.1" 500 325 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0"
<localhost>:<customport> <networkdeviceip> - - [07/Sep/2022:22:14:34 +0100] "POST /p/i/?c=importExport&a=import HTTP/1.1" 500 325 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0"
```

**Environment information (please complete the following information):**
- Operating System: Debian GNU/Linux 11 (bullseye)
- Kernel: Linux 5.15.56-v8+
- Architecture: arm64
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0
- FreshRSS version: 1.19.2
- Database version: mariadb-server-10.5/stable,now 1:10.5.15-0+deb11u1 arm64 | also tried php7.4-sqlite3/stable-security,now 7.4.30-1+deb11u1 arm64
- PHP version: 7.4
- Installation type: ?

**Additional context**
Attempted these steps in both `/etc/php/7.4/apache2/php.ini` and `/etc/php7.4/fpm/php.ini
```
Three settings are relevant, and must all be high enough, for instance:
memory_limit = 256M
post_max_size = 64M
upload_max_filesize = 48M
```
_Originally posted by @Alkarex in https://github.com/FreshRSS/FreshRSS/issues/1890#issuecomment-537663923_

**Comment by Alkarex** [comment]
The OPML example you give is invalid:

http://opml.org/spec2.opml
> Every outline element must have at least a text attribute

But will add a workaround anyway.

What tool produced that OPML?

**Comment by Alkarex** [comment]
@pastram-i Would you be able to test https://github.com/FreshRSS/FreshRSS/pull/4591 ?

**Comment by bl-ey** [comment]
Apologizes @Alkarex - busy day. 

I should be able to test tonight or tomorrow, ty. 

I used https://opml-gen.ovh/
