### ISSUE TITLE
[BUG] Error when trying to add feed url

### ISSUE THREAD

**Issue by Creat1veM1nd** [FreshRSS/FreshRSS#5136]
**Describe the bug**
Not able to add feeds. 
When trying to add any of the feeds given in the file
[feeds.txt](https://github.com/FreshRSS/FreshRSS/files/10812511/feeds.txt)
I get an error saying that feed can not be add, forcing with suggested option does not work either

>2023-02-23 11:28:27 | Unknown error for feed [https://www.2daygeek.com/feed/]
>  | 2023-02-23 11:28:15 | Unknown error for feed [https://ich-glaube-es-hackt.de/feed/]
[...]

The feeds are reachable when calling URLs via browser.

**To Reproduce**
Try to add a feed given in the provided txt file

**Expected behavior**
Adding feed without problems

**Environment information (please complete the following information):**
- Device: PC
- OS: Windows 10
- Browser: Chrome
- FreshRSS version: 1.20.2
- Database version: mysql  Ver 14.14 Distrib 5.7.40-43,
- PHP version:  8.1.16
- Installation type: Manual

My FreshRss installation is a new one, no extensions added.

**Comment by Alkarex** [comment]
Hello,
Could you check in the logs some of the initial errors (before the *Unknown error for feed*)?
The two feeds https://www.2daygeek.com/feed/ and https://ich-glaube-es-hackt.de/feed/ work for me.

Could you try the following from the same computer than where your FreshRSS is running?

```sh
curl -v 'https://ich-glaube-es-hackt.de/feed/'
```

**Comment by Creat1veM1nd** [comment]
Hello,

beside those "Unknown error for feed" no other errors in the logs of fresh rss. (I looked up admin -> protocols, is that the right place ?)

curl command brought the following output, directly called from my server on which freshrss is running.
[curl.txt](https://github.com/FreshRSS/FreshRSS/files/10816484/curl.txt)

Since the two urls work for you, I guess something with my server or configuration is different. 

I found this in my server error log

```
[Thu Feb 23 11:22:16 2023] [php:error] [pid 6021] [client <myip>] [host <myhost>] PHP Fatal error:  Uncaught Error: Call to undefined function syslog() in /<path to freshrss>/rss/lib/SimplePie/SimplePie/File.php:83
Stack trace:
#0 [internal function]: SimplePie_File-]__construct('https://www.sch...', 15, 5, Array, 'FreshRSS/1.20.2...', false, Array, true)
#1 /<path to freshrss>/rss/lib/SimplePie/SimplePie/Registry.php(183): ReflectionClass-]newInstanceArgs(Array)
#2 /<path to freshrss>/rss/lib/SimplePie/SimplePie.php(1759): SimplePie_Registry-]create('File', Array)
#3 /<path to freshrss>/rss/lib/SimplePie/SimplePie.php(1493): SimplePie-]fetch_data(Object(SimplePie_Cache_File))
#4 /<path to freshrss>/rss/app/Models/Feed.php(380): SimplePie-]init()
#5 /<path to freshrss>/rss/app/Controllers/feedController.php(393): FreshRSS_Feed-]load(false, true)
#6 /<path to freshrss>/rss/app/Controllers/feedController.php(647): FreshRSS_feed_Controller::actualizeFeed('16', false, false, NULL, true, 10)
#7 /<path to freshrss>/rss/lib/Minz/Dispatcher.php(119): FreshRSS_feed_Controller-]actualizeAction()
#8 /<path to freshrss>/rss/lib/Minz/Dispatcher.php(48): Minz_Dispatcher-]launchAction('actualizeAction')
#9 /<path to freshrss>/rss/lib/Minz/FrontController.php(58): Minz_Dispatcher-]run()
#10 /<path to freshrss>/rss/p/i/index.php(57): Minz_FrontController-]run()\n#11 {main}
  thrown in /<path to freshrss>/rss/lib/SimplePie/SimplePie/File.php on line 83
```
for every rss feed I tried to add.
I set my PHP version to 8.0 (the lowest one I can choose) but got the same error. Maybe this helps ?

Let me know what else I shall look up!

**Comment by Alkarex** [comment]
It looks like some core PHP functions such as `syslog()` are disabled in your PHP configuration.
Could you please try our latest edge version of FreshRSS? I have added a workaround https://github.com/FreshRSS/FreshRSS/pull/5054 for this precise case

**Comment by Creat1veM1nd** [comment]
According to my phpinfo it is indeed disabled and sadly no option to enable it on my hosted server (as far as I can see). 

I just tried the latest edge version and add feed plus importing them via OPML works as expected!
