### ISSUE TITLE
[BUG] Update SimplePie dependency for PHP 8.1 / 8.2 compatibility

### ISSUE THREAD

**Issue by kgraefe** [FreshRSS/FreshRSS#5195]
**Describe the bug**
`php ./app/actualize_script.php` failed for me because of https://github.com/simplepie/simplepie/pull/747:

```
❯ php --version
PHP 8.2.3 (cli) (built: Mar  1 2023 12:14:45) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.3, Copyright (c) Zend Technologies
❯ php ./app/actualize_script.php
FreshRSS starting feeds actualization at 2023-03-12T15:31:53+00:00
FreshRSS actualize kgraefe…
Results:
kgraefe PHP Fatal error:  Uncaught Error: Call to undefined function int() in /var/www/paktolos.net/feeds/lib/SimplePie/SimplePie/Misc.php:159
Stack trace:
#0 /var/www/paktolos.net/feeds/lib/SimplePie/SimplePie/Registry.php(222): SimplePie_Misc::error('A feed could no...', 1024, '/var/www/paktol...', 1829)
#1 /var/www/paktolos.net/feeds/lib/SimplePie/SimplePie.php(1829): SimplePie_Registry->call('Misc', 'error', Array)
#2 /var/www/paktolos.net/feeds/lib/SimplePie/SimplePie.php(1499): SimplePie->fetch_data(Object(SimplePie_Cache_File))
#3 /var/www/paktolos.net/feeds/app/Models/Feed.php(386): SimplePie->init()
#4 /var/www/paktolos.net/feeds/app/Controllers/feedController.php(399): FreshRSS_Feed->load(false, false)
#5 /var/www/paktolos.net/feeds/app/Controllers/feedController.php(653): FreshRSS_feed_Controller::actualizeFeed(false, false, true, NULL, false, 10)
#6 /var/www/paktolos.net/feeds/lib/Minz/Dispatcher.php(119): FreshRSS_feed_Controller->actualizeAction()
#7 /var/www/paktolos.net/feeds/lib/Minz/Dispatcher.php(46): Minz_Dispatcher->launchAction('actualizeAction')
#8 /var/www/paktolos.net/feeds/lib/Minz/FrontController.php(58): Minz_Dispatcher->run()
#9 /var/www/paktolos.net/feeds/app/actualize_script.php(83): Minz_FrontController->run()
#10 {main}
  thrown in /var/www/paktolos.net/feeds/lib/SimplePie/SimplePie/Misc.php on line 159
```
 Manually applying the change fixes it for me.

**To Reproduce**
Configure FreshRSS with an erroneous feed and run `./app/actualize_script.php` with PHP 8.2.

**Expected behavior**
The script should succeed and log an appropriate error description 

**Environment information (please complete the following information):**
- Device: amd64 server
- OS: Debian 11
- Browser: n/a
- FreshRSS version: 1.21.0 
- Database version: MariaDB
- PHP version: 8.2 (Official Docker image `php:8.2-fpm`+ pdo + pdo_mysql + zip extensions)
- Installation type: manual

**Comment by Alkarex** [comment]
Thanks for the bug report. Should be fixed with https://github.com/FreshRSS/FreshRSS/pull/5199
Tests welcome
