### ISSUE TITLE
[BUG] Fatal error:  Uncaught TypeError: FreshRSS_FeedDAO::searchById(): Argument

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#5227]
**Describe the bug**
```
Fatal error:  Uncaught TypeError: FreshRSS_FeedDAO::searchById(): Argument #1 ($id) must be of type int, null given, called in foo\bar\app\Controllers\statsController.php on line 208 and defined in foo\bar\app\Models\FeedDAO.php:287
Stack trace:
#0 foo\bar\app\Controllers\statsController.php(208): FreshRSS_FeedDAO->searchById(NULL)
#1 foo\bar\lib\Minz\Dispatcher.php(119): FreshRSS_stats_Controller->repartitionAction()
#2 foo\bar\lib\Minz\Dispatcher.php(48): Minz_Dispatcher->launchAction('repartitionActi...')
#3 foo\bar\lib\Minz\FrontController.php(58): Minz_Dispatcher->run()
#4 foo\bar\p\i\index.php(57): Minz_FrontController->run()
#5 {main}
  thrown in foo\bar\app\Models\FeedDAO.php on line 287
```

**To Reproduce**
1. Go to `Articles repartition`
![grafik](https://user-images.githubusercontent.com/1645099/227783254-444ef1d8-817c-403b-8b7e-0aa3a913addf.png)
2. see the error

**Expected behavior**
see the content of `Articles repartition` without an error

**Environment information (please complete the following information):**
- FreshRSS version: current 1.21.1-dev

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/5228
