### ISSUE TITLE
[BUG] Uncaught TypeError in app/Models/Feed.php

### ISSUE THREAD

**Issue by sesom42** [FreshRSS/FreshRSS#5928]
**Describe the bug**
Recently, fatal errors have been occurring again and again in PHP when updating different feeds. The error messages always look similar with different feeds:

```
Dec  6 11:00:01 web php[100493]: FreshRSS starting feeds actualization at 2023-12-06T11:00:01+01:00
Dec  6 11:00:01 web FreshRSS[100493]: FreshRSS actualize shogun…
Dec  6 11:00:01 web php[100493]: FreshRSS actualize shogun…
Dec  6 11:00:01 web FreshRSS[100493]: SimplePie GET https://nachrichtenfeeds.br.de/rdf/boards/QXAPkQJ
Dec  6 11:00:01 web FreshRSS[100493]: SimplePie MD5 cache no match for https://nachrichtenfeeds.br.de/rdf/boards/QXAPkQJ
Dec  6 11:00:01 web php[100493]: PHP Fatal error:  Uncaught TypeError: Argument 4 passed to FreshRSS_Entry::__construct() must be of the type string, bool given, called in /srv/FreshRSS/app/Models/Feed.php on line 592 and defined in /srv/FreshRSS/app/Models/Entry.php:38
Dec  6 11:00:01 web php[100493]: Stack trace:
Dec  6 11:00:01 web php[100493]: #0 /srv/FreshRSS/app/Models/Feed.php(592): FreshRSS_Entry->__construct()
Dec  6 11:00:01 web php[100493]: #1 /srv/FreshRSS/app/Controllers/feedController.php(484): FreshRSS_Feed->loadEntries()
Dec  6 11:00:01 web php[100493]: #2 /srv/FreshRSS/app/Controllers/feedController.php(718): FreshRSS_feed_Controller::actualizeFeeds()
Dec  6 11:00:01 web php[100493]: #3 /srv/FreshRSS/lib/Minz/Dispatcher.php(120): FreshRSS_feed_Controller->actualizeAction()
Dec  6 11:00:01 web php[100493]: #4 /srv/FreshRSS/lib/Minz/Dispatcher.php(51): Minz_Dispatcher->launchAction()
Dec  6 11:00:01 web php[100493]: #5 /srv/FreshRSS/lib/Minz/FrontController.php(61): Minz_Dispatcher->run()
Dec  6 11:00:01 web php[100493]: #6 /srv/FreshRSS/app/actualize_script.php(110): Minz_FrontController->run()
Dec  6 11:00:01 web php[100493]: #7 {main}
Dec  6 11:00:01 web php[100493]:   thrown in /srv/FreshRSS/app/Models/Entry.php on line 38
Dec  6 11:00:01 web php[100493]: Results:
Dec  6 11:00:01 web php[100493]: shogun
Dec  6 11:00:01 web systemd[1]: freshrss.service: Main process exited, code=exited, status=255/EXCEPTION
Dec  6 11:00:01 web systemd[1]: freshrss.service: Failed with result 'exit-code'.
```

**To Reproduce**
I cannot say how the error can be caused. The errors have been occurring since the last git pull.

**Environment information (please complete the following information):**
- OS: Debian 11.8
- FreshRSS version: 1.22.2-dev
- Database version: MariaDB 10.5.21
- PHP version: PHP 7.4.33

**Comment by Alkarex** [comment]
Thanks for the bug report.
Should be fixed by https://github.com/FreshRSS/FreshRSS/pull/5929
Feedback welcome
