### ISSUE TITLE
[Bug] Cronjob broken

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#6547]
### Describe the bug

Following error from FreshRSS actualize feed update cronjob:
```
PHP Fatal error:  Uncaught Error: Typed property FreshRSS_View::$description must not be accessed before initialization in .../app/views/index/rss.phtml:12
Stack trace:
#0 .../lib/Minz/View.php(94): include()
#1 .../lib/Minz/View.php(116): Minz_View->includeFile()
#2 .../lib/Minz/View.php(123): Minz_View->render()
#3 .../app/Models/Feed.php(810): Minz_View->renderToString()
#4 .../app/Controllers/feedController.php(489): FreshRSS_Feed->loadHtmlXpath()
#5 .../app/Controllers/feedController.php(861): FreshRSS_feed_Controller::actualizeFeeds()
#6 .../lib/Minz/Dispatcher.php(120): FreshRSS_feed_Controller->actualizeAction()
#7 .../lib/Minz/Dispatcher.php(51): Minz_Dispatcher->launchAction()
#8 .../lib/Minz/FrontController.php(61): Minz_Dispatcher->run()
#9 .../app/actualize_script.php(106): Minz_FrontController->run()
#10 {main}
  thrown in .../app/views/index/rss.phtml on line 12
```

It leads to a broken update cronjob. Feeds will not be updated.

### To Reproduce

 feed update cronjob

### FreshRSS version

1.24.2-dev

### Environment information

- Database version: Mysql
- PHP version: PHP 8.0

**Comment by Alkarex** [comment]
Regression from https://github.com/FreshRSS/FreshRSS/pull/6541
Fix coming

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/6548
