### ISSUE TITLE
[Bug] FreshRSS Can`t update to the latest Version

### ISSUE THREAD

**Issue by AkarinLiu** [FreshRSS/FreshRSS#6963]
### Describe the bug

When using Fresh RSS, it cannot be updated normally. After the update, a 500 error is reported and the update fails.

### To Reproduce

1. Click the gear icon 
2. Click the Update
3. Click the Check Update button 
4. Click Apply
5. See 500 Error

### Expected behavior

Finsh Updated

### FreshRSS version

1.25.0-dev

### Environment information

- Database version: MariaDB 10.11 [e.g. Mysql 5.7, SQLite]
- PHP version: PHP8.3 [e.g. PHP 8.1]
- Installation type: 1Panel [e.g. Docker, Docker image source, git, Yunohost]
-Web server type: OpenResty [e.g. Apache, nginx]
- Device: [e.g. Redmi K70E]
- OS: Android 14 [e.g. Ubuntu 22.04, Win10, MacOS14]
- Browser: Edge 130.0.2849.46 [e.g. Firefox 124]

### Additional context

I don't know how to change update Chanel, I want change to the stable Chanel.
Instance URL：https://rss.akarinliu.com

**Comment by Alkarex** [comment]
Hello,
Do yo have any logs with some details of the errors / warnings?

**Comment by AkarinLiu** [comment]
I send you logfile.

邮件来自 Outlook for Windows
________________________________
发件人: Alexandre Alapetite ***@***.***>
发送时间: 2024年11月1日 17:39
收件人: FreshRSS/FreshRSS ***@***.***>
抄送: 阿卡林刘 ***@***.***>; Author ***@***.***>
主题: Re: [FreshRSS/FreshRSS] [Bug] FreshRSS Can`t update to the latest Version (Issue #6963)


Hello,
Do yo have any logs with some details of the errors / warnings?

―

**Comment by AkarinLiu** [comment]
```
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:41:06 +0800 "POST /index.php" 302
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:41:07 +0800 "GET /i/index.php" 200
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:42:06 +0800 "POST /index.php" 302
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:42:06 +0800 "GET /i/index.php" 200
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:43:06 +0800 "POST /index.php" 302
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:43:07 +0800 "GET /i/index.php" 200
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:44:00 +0800 "POST /api/greader.php" 200
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:44:01 +0800 "GET /api/greader.php" 200
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:44:01 +0800 "GET /api/greader.php" 200
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:44:01 +0800 "GET /api/greader.php" 200
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:44:01 +0800 "GET /api/greader.php" 200
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:44:01 +0800 "POST /api/greader.php" 200
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:44:02 +0800 "GET /api/greader.php" 200
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:44:02 +0800 "POST /api/greader.php" 200
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:44:06 +0800 "POST /index.php" 302
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:44:07 +0800 "GET /i/index.php" 200
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:45:06 +0800 "POST /index.php" 302
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:45:07 +0800 "GET /i/index.php" 200
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:46:07 +0800 "POST /index.php" 302
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:46:07 +0800 "GET /i/index.php" 200
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:47:06 +0800 "POST /index.php" 302
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:47:06 +0800 "GET /i/index.php" 200
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:48:06 +0800 "POST /index.php" 302
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:48:07 +0800 "GET /i/index.php" 200
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:49:06 +0800 "POST /index.php" 302
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:49:07 +0800 "GET /i/index.php" 200
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:50:05 +0800 "POST /index.php" 302
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:50:06 +0800 "GET /i/index.php" 200
[2K1Panel-php8-NDc6  | NOTICE: PHP message: PHP Deprecated:  mb_convert_encoding(): Handling HTML entities via mbstring is deprecated; use htmlspecialchars, htmlentities, or mb_encode_numericentity/mb_decode_numericentity instead in /www/sites/rss.akarinliu.com/index/FreshRSS/extensions/xExtension-ImageProxy/extension.php on line 123
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:50:49 +0800 "GET /i/index.php" 200
[2K1Panel-php8-NDc6  | NOTICE: PHP message: PHP Deprecated:  Creation of dynamic property Minz_View::$icon_url_in is deprecated in /www/sites/rss.akarinliu.com/index/FreshRSS/extensions/xExtension-QuickCollapse/Controllers/quickCollapseController.php on line 16
[2K1Panel-php8-NDc6  | NOTICE: PHP message: PHP Deprecated:  Creation of dynamic property Minz_View::$icon_url_out is deprecated in /www/sites/rss.akarinliu.com/index/FreshRSS/extensions/xExtension-QuickCollapse/Controllers/quickCollapseController.php on line 17
[2K1Panel-php8-NDc6  | NOTICE: PHP message: PHP Deprecated:  Creation of dynamic property Minz_View::$i18n_toggle_collapse is deprecated in /www/sites/rss.akarinliu.com/index/FreshRSS/extensions/xExtension-QuickCollapse/Controllers/quickCollapseController.php on line 19
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:50:49 +0800 "GET /i/index.php" 200
[2K1Panel-php8-NDc6  | NOTICE: PHP message: PHP Deprecated:  mb_convert_encoding(): Handling HTML entities via mbstring is deprecated; use htmlspecialchars, htmlentities, or mb_encode_numericentity/mb_decode_numericentity instead in /www/sites/rss.akarinliu.com/index/FreshRSS/extensions/xExtension-ImageProxy/extension.php on line 123
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:50:50 +0800 "GET /i/index.php" 200
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:50:55 +0800 "GET /i/index.php" 200
[2K1Panel-php8-NDc6  | NOTICE: PHP message: PHP Deprecated:  Creation of dynamic property Minz_View::$icon_url_in is deprecated in /www/sites/rss.akarinliu.com/index/FreshRSS/extensions/xExtension-QuickCollapse/Controllers/quickCollapseController.php on line 16
[2K1Panel-php8-NDc6  | NOTICE: PHP message: PHP Deprecated:  Creation of dynamic property Minz_View::$icon_url_out is deprecated in /www/sites/rss.akarinliu.com/index/FreshRSS/extensions/xExtension-QuickCollapse/Controllers/quickCollapseController.php on line 17
[2K1Panel-php8-NDc6  | NOTICE: PHP message: PHP Deprecated:  Creation of dynamic property Minz_View::$i18n_toggle_collapse is deprecated in /www/sites/rss.akarinliu.com/index/FreshRSS/extensions/xExtension-QuickCollapse/Controllers/quickCollapseController.php on line 19
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:50:55 +0800 "GET /i/index.php" 200
[2K1Panel-php8-NDc6  | NOTICE: PHP message: PHP Warning:  opendir(/www/sites/rss.akarinliu.com/index/FreshRSS/data/PubSubHubbub/feeds/5304075a3178fcf50ab5025f6e1b08853249218f): Failed to open directory: Permission denied in /www/sites/rss.akarinliu.com/index/FreshRSS/data/update.php on line 29
[2K1Panel-php8-NDc6  | NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: readdir(): Argument #1 ($dir_handle) must be of type resource or null, false given in /www/sites/rss.akarinliu.com/index/FreshRSS/data/update.php:31
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:50:57 +0800 "GET /i/index.php" 500
[2K1Panel-php8-NDc6  | Stack trace:
[2K1Panel-php8-NDc6  | #0 /www/sites/rss.akarinliu.com/index/FreshRSS/data/update.php(31): readdir(false)
[2K1Panel-php8-NDc6  | #1 /www/sites/rss.akarinliu.com/index/FreshRSS/data/update.php(34): recurse_copy('/www/sites/rss....', '/www/sites/rss....')
[2K1Panel-php8-NDc6  | #2 /www/sites/rss.akarinliu.com/index/FreshRSS/data/update.php(34): recurse_copy('/www/sites/rss....', '/www/sites/rss....')
[2K1Panel-php8-NDc6  | #3 /www/sites/rss.akarinliu.com/index/FreshRSS/data/update.php(34): recurse_copy('/www/sites/rss....', '/www/sites/rss....')
[2K1Panel-php8-NDc6  | #4 /www/sites/rss.akarinliu.com/index/FreshRSS/data/update.php(58): recurse_copy('/www/sites/rss....', '/www/sites/rss....')
[2K1Panel-php8-NDc6  | #5 /www/sites/rss.akarinliu.com/index/FreshRSS/data/update.php(234): data_backup()
[2K1Panel-php8-NDc6  | #6 /www/sites/rss.akarinliu.com/index/FreshRSS/app/Controllers/updateController.php(308): apply_update()
[2K1Panel-php8-NDc6  | #7 /www/sites/rss.akarinliu.com/index/FreshRSS/lib/Minz/Dispatcher.php(120): FreshRSS_update_Controller->applyAction()
[2K1Panel-php8-NDc6  | #8 /www/sites/rss.akarinliu.com/index/FreshRSS/lib/Minz/Dispatcher.php(49): Minz_Dispatcher->launchAction('applyAction')
[2K1Panel-php8-NDc6  | #9 /www/sites/rss.akarinliu.com/index/FreshRSS/lib/Minz/FrontController.php(61): Minz_Dispatcher->run()
[2K1Panel-php8-NDc6  | #10 /www/sites/rss.akarinliu.com/index/FreshRSS/p/i/index.php(59): Minz_FrontController->run()
[2K1Panel-php8-NDc6  | #11 {main}
[2K1Panel-php8-NDc6  |   thrown in /www/sites/rss.akarinliu.com/index/FreshRSS/data/update.php on line 31
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:51:06 +0800 "POST /index.php" 302
[2K1Panel-php8-NDc6  | 172.19.0.1 -  01/Nov/2024:18:51:07 +0800 "GET /i/index.php" 200
```

**Comment by AkarinLiu** [comment]
Sometimes it can be updated, but sometimes it cannot be updated normally due to update server problems.

**Comment by Alkarex** [comment]
As you can see in your logs, you get some `Permission denied` errors, so you need to re-apply your access rights properly.

https://freshrss.github.io/FreshRSS/en/admins/06_LinuxInstall.html#part-2-installing-freshrss

Depending on your platform, something like:

```sh
cd FreshRSS/
sudo cli/access-permissions.sh
# only for Web-based updates
sudo chown www-data:www-data -R .
```

**Comment by Alkarex** [comment]
You could also consider updating to a more reliable update method, for instance based on git:
https://github.com/FreshRSS/FreshRSS/discussions/6769

**Comment by math-GH** [comment]
> ```
> �[2K1Panel-php8-NDc6  | NOTICE: PHP message: PHP Warning:  opendir(/www/sites/rss.akarinliu.com/index/FreshRSS/data/PubSubHubbub/feeds/5304075a3178fcf50ab5025f6e1b08853249218f): Failed to open directory: Permission denied in /www/sites/rss.akarinliu.com/index/FreshRSS/data/update.php on line 29
> �[2K1Panel-php8-NDc6  | NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: readdir(): Argument #1 ($dir_handle) must be of type resource or null, false given in /www/sites/rss.akarinliu.com/index/FreshRSS/data/update.php:31
> ```

this fatal error needs a fix too

**Comment by Alkarex** [comment]
The `readdir` error? It is a consequence of the wrong access rights

**Comment by mjysci** [comment]
I also encountered a 500 error after a web update, so I switched the installation method to Git. Then, I used `git checkout` to test some versions. It turns out `1.24.3` is the latest working version for me, while `1.25.0` resulted in a 500 error.

**Comment by Alkarex** [comment]
@mjysci What PHP version do you have? FreshRSS 1.25 requires PHP 8.1+
Otherwise, please try to find in your logs an error message

**Comment by mjysci** [comment]
@Alkarex I think this is the issue for me - my server is running PHP 7.4. I'll stick with `1.24.3` for now, because upgrading to 8.x might break other programs also running on that server. Thanks!

**Comment by Alkarex** [comment]
@mjysci Yes, that was the idea of [1.24.3](https://github.com/FreshRSS/FreshRSS/releases/tag/1.24.3):

> This is a quality-focussed release for the [1.24.x series](https://github.com/FreshRSS/FreshRSS/releases/tag/1.24.2) meant to provide a good product to people blocked on PHP 7.4, while we will increase the requirements to PHP 8.1+ from the next release.

Alternatively, you could consider using [our Docker distribution](https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md) to deploy FreshRSS
