### ISSUE TITLE
[Bug] Another "Error during context user init!"

### ISSUE THREAD

**Issue by cadric** [FreshRSS/FreshRSS#7080]
### Describe the bug

Server have been running for 2 weeks without problems. 
Today I am getting a "_Error during context user init!_"

I am using Fedora server 41, with caddy in a podman container. FreshRSS is installed from git.
I don't really know what to do from here, to get it back up.

_**in FreshRSS/data/users/cadric/log.txt**_

```
#0 /home/cadric/caddyweb/site/FreshRSS/extensions/xExtension-RedditImage-1.2.0/Processor/BeforeInsertProcessor.php(52): RedditImage\Content->__construct()
#1 /home/cadric/caddyweb/site/FreshRSS/lib/Minz/ExtensionManager.php(375): RedditImage\Processor\BeforeInsertProcessor->process()
#2 /home/cadric/caddyweb/site/FreshRSS/lib/Minz/ExtensionManager.php(345): Minz_ExtensionManager::callOneToOne()
#3 /home/cadric/caddyweb/site/FreshRSS/app/Controllers/feedController.php(580): Minz_ExtensionManager::callHook()
#4 /home/cadric/caddyweb/site/FreshRSS/app/Controllers/feedController.php(855): FreshRSS_feed_Controller::actualizeFeeds()
#5 /home/cadric/caddyweb/site/FreshRSS/lib/Minz/Dispatcher.php(120): FreshRSS_feed_Controller->actualizeAction()
#6 /home/cadric/caddyweb/site/FreshRSS/lib/Minz/Dispatcher.php(49): Minz_Dispatcher->launchAction()
#7 /home/cadric/caddyweb/site/FreshRSS/lib/Minz/FrontController.php(61): Minz_Dispatcher->run()
#8 /home/cadric/caddyweb/site/FreshRSS/app/actualize_script.php(106): Minz_FrontController->run()
#9 {main}
[Mon, 09 Dec 2024 04:40:44 +0000] [warning] --- A feed could not be found at `http://rssfeeds.usatoday.com/usatoday-NewsTopStories`; the status code is `200` and content-type is `text/html; charset=utf-8` [http>
[Mon, 09 Dec 2024 06:01:06 +0000] [warning] --- A feed could not be found at `http://rssfeeds.usatoday.com/usatoday-NewsTopStories`; the status code is `200` and content-type is `text/html; charset=utf-8` [http>
[Mon, 09 Dec 2024 06:41:02 +0000] [warning] --- A feed could not be found at `http://rssfeeds.usatoday.com/usatoday-NewsTopStories`; the status code is `200` and content-type is `text/html; charset=utf-8` [http>
[Mon, 09 Dec 2024 07:20:02 +0000] [error] --- SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",14,"unable to open database file"] while updating feed 3
[Mon, 09 Dec 2024 07:20:02 +0000] [warning] --- FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",14,"unable to open database file"]
[Mon, 09 Dec 2024 07:20:03 +0000] [error] --- SQL error FreshRSS_EntryDAO::updateLastSeenUnchanged["HY000",14,"unable to open database file"] while updating feed 2
[Mon, 09 Dec 2024 07:20:03 +0000] [warning] --- FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",14,"unable to open database file"]
[Mon, 09 Dec 2024 07:20:04 +0000] [error] --- SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",14,"unable to open database file"] while updating feed 4
[Mon, 09 Dec 2024 07:20:04 +0000] [warning] --- FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",14,"unable to open database file"]
[Mon, 09 Dec 2024 07:20:04 +0000] [error] --- SQL error FreshRSS_EntryDAO::addEntry["HY000",14,"unable to open database file"] while adding entry in feed 5 with title: Efterforskes for landsforr  deri: Pr  side>
[Mon, 09 Dec 2024 07:20:04 +0000] [error] --- SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",14,"unable to open database file"] while updating feed 5
[Mon, 09 Dec 2024 07:20:04 +0000] [warning] --- FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",14,"unable to open database file"]
[Mon, 09 Dec 2024 07:20:04 +0000] [error] --- SQL error FreshRSS_EntryDAO::addEntry["HY000",21,"bad parameter or other API misuse"] while adding entry in feed 6 with title: Alvorlig f  rdselsulykke: Fodg  nger >
[Mon, 09 Dec 2024 07:20:04 +0000] [error] --- SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",14,"unable to open database file"] while updating feed 6
[Mon, 09 Dec 2024 07:20:04 +0000] [warning] --- FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",14,"unable to open database file"]
[Mon, 09 Dec 2024 07:20:04 +0000] [error] --- SQL error FreshRSS_EntryDAO::addEntry["HY000",21,"bad parameter or other API misuse"] while adding entry in feed 9 with title: Minister rejser til Bruxelles for at >
[Mon, 09 Dec 2024 07:20:04 +0000] [error] --- SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",14,"unable to open database file"] while updating feed 9
[Mon, 09 Dec 2024 07:20:04 +0000] [warning] --- FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",14,"unable to open database file"]
[Mon, 09 Dec 2024 07:20:05 +0000] [error] --- SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",14,"unable to open database file"] while updating feed 10
[Mon, 09 Dec 2024 07:20:05 +0000] [warning] --- FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",14,"unable to open database file"]
[Mon, 09 Dec 2024 07:20:06 +0000] [error] --- SQL error FreshRSS_EntryDAO::updateLastSeenUnchanged["HY000",14,"unable to open database file"] while updating feed 11
[Mon, 09 Dec 2024 07:20:06 +0000] [warning] --- FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",14,"unable to open database file"]
[Mon, 09 Dec 2024 07:20:06 +0000] [error] --- SQL error FreshRSS_EntryDAO::updateLastSeenUnchanged["HY000",14,"unable to open database file"] while updating feed 12
[Mon, 09 Dec 2024 07:20:06 +0000] [warning] --- FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",14,"unable to open database file"]
[Mon, 09 Dec 2024 07:20:07 +0000] [error] --- SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",14,"unable to open database file"] while updating feed 13
[Mon, 09 Dec 2024 07:20:07 +0000] [warning] --- FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",14,"unable to open database file"]
[Mon, 09 Dec 2024 07:20:07 +0000] [error] --- SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",14,"unable to open database file"] while updating feed 14
[Mon, 09 Dec 2024 07:20:07 +0000] [warning] --- FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",14,"unable to open database file"]
[Mon, 09 Dec 2024 07:20:07 +0000] [error] --- SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",14,"unable to open database file"] while updating feed 15
[Mon, 09 Dec 2024 07:20:07 +0000] [warning] --- FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",14,"unable to open database file"]
[Mon, 09 Dec 2024 07:20:08 +0000] [error] --- SQL error FreshRSS_EntryDAO::addEntry["HY000",21,"bad parameter or other API misuse"] while adding entry in feed 16 with title: r/Ultralight - &quot;The Weekly&quot>
[Mon, 09 Dec 2024 07:20:08 +0000] [error] --- SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",14,"unable to open database file"] while updating feed 16
[Mon, 09 Dec 2024 07:20:08 +0000] [warning] --- FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",14,"unable to open database file"]
[Mon, 09 Dec 2024 07:20:09 +0000] [error] --- SQL error FreshRSS_EntryDAO::updateEntry["HY000",14,"unable to open database file"] while updating entry with GUID t3_1ha0e1p in feed 17
[Mon, 09 Dec 2024 07:20:12 +0000] [error] --- SQL error FreshRSS_EntryDAO::updateEntry["HY000",21,"bad parameter or other API misuse"] while updating entry with GUID t3_1h9eo0h in feed 17
[Mon, 09 Dec 2024 07:20:12 +0000] [error] --- SQL error FreshRSS_EntryDAO::updateEntry["HY000",21,"bad parameter or other API misuse"] while updating entry with GUID t3_1ha2w5u in feed 17
[Mon, 09 Dec 2024 07
```

### To Reproduce

1. Go to platoon.dk
2. Click on '…'
3. Scroll down to '…'

### FreshRSS version

1.24.3

### Environment information

- Database version: sqlite3 3.45.3 
- PHP version: PHP Version 8.3.13
- Installation type: git
-Web server type: caddy
- OS: Fedora Server 41
- Browser: Any browser

**Comment by Alkarex** [comment]
Hello,
Just to be sure, try also to disable any FreshRSS extension if possible, as some of your errors in the log come from *RedditImage*.
Otherwise, *Error during context user init* can be a sign of wrong volume settings.

https://github.com/FreshRSS/FreshRSS/blob/3dc997d43289b6b05bf4d729d83b5da57045fc6c/app/FreshRSS.php#L51

Inside your container, try to: `ls -alh data/users/`

**Comment by davralin** [comment]
> Inside your container, try to: `ls -alh data/users/`

I wasn't sure what it was supposed to say there, but I had the same issue with my install (as in, "Error during context user init!").

I fixed it with chown -R www-data:www-data data/users/ inside the container.

**Comment by Alkarex** [comment]
@davralin What FreshRSS Docker image, more precisely? And can you explain more how it happened?

**Comment by MattCost** [comment]
I'm seeing the same issue, trying to run in hosted in an Azure Container Instance, using an Azure Storage Act for the volume mounts. Basically trying to follow the quickstart, but hosting in azure. 

When I ran locally via Docker, on Fedora 41, everything worked fine. 

In Azure, during initial setup, all checks are green, I enter a username and password and hit submit, and the operation takes a while. It claims to succeed, but doesn't advance to the next step automatically. If I click Continue, I am dumped at the `Error during context user init!` page.

I did see an error in the logs about the Database being locked, but I didn't copy it in time, so ive lost the exact error msg.


```
      volumeMounts:
      - mountPath: /var/www/FreshRSS/data
        volumeName: data
      - mountPath: /var/www/FreshRSS/extensions
        volumeName: extensions
```

```
    volumes:
    - name: data
      storageName: file-share2
      storageType: AzureFile
    - name: extensions
      storageName: file-share2
      storageType: AzureFile
```

Volume mounts are setup per the quick start guide. The volumes are defined to be linked to `file-share2` in my storage act, with read/write access.
I can see the following folders get created in the storage act.

![Image](https://github.com/user-attachments/assets/aaaf6605-aa69-4c1a-a3fb-0d599e5958d9)

**Comment by davralin** [comment]
> [@davralin](https://github.com/davralin) What FreshRSS Docker image, more precisely? And can you explain more how it happened?

Forgot to reply, it was with the official image. However, it was due to a faulty restore by me, so they original fault was mine.

I mainly commented to point out that the issue is probably related to permissions.
